### ISSUE TITLE
大神能帮我看看为啥报错

### ISSUE THREAD

**Issue by qincg** [zJiaJun/adult-download#2]
报错信息如下：
java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(SocketInputStream.java)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at okio.Okio$2.read(Okio.java:140)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:238)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:325)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:314)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:210)
	at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:184)
	at okhttp3.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:125)
	at okhttp3.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:775)
	at okhttp3.internal.http.HttpEngine.access$200(HttpEngine.java:86)
	at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:760)
	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:212)
	at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:733)
	at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:613)
	at okhttp3.RealCall.getResponse(RealCall.java:244)
已经翻墙了

**Comment by huangtiansheng** [comment]
由于国内我们翻墙一般用的http proxy, 只需要在RetrofitClient里的httpClient 上加上代理设置即可。
![default](https://user-images.githubusercontent.com/28618356/35220131-23081ed6-ffb0-11e7-9c1d-0cc513d3f50f.png)
端口号可能需要根据代理设置的端口号而定，正常来说是1080.

**Comment by zJiaJun** [comment]
增加代理配置，目前仅支持socks.
adult.conf proxy {}
